# Generated by Django 4.2.16 on 2025-03-29 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='motor',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
