# Generated by Django 4.2.16 on 2025-04-05 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0002_motor_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='motor',
            name='UIN',
            field=models.PositiveIntegerField(null=True, unique=True),
        ),
    ]
