# Generated by Django 4.2.16 on 2025-04-05 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0003_alter_motor_uin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='motor',
            name='UIN',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
