# Generated by Django 4.2.16 on 2025-04-10 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0004_alter_motor_uin'),
    ]

    operations = [
        migrations.AddField(
            model_name='valve',
            name='valve_id',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
