# Generated by Django 4.2.16 on 2025-05-30 11:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0005_valve_valve_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='farm',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
