# Generated by Django 4.2.16 on 2025-05-31 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0006_farm_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='valve',
            name='status',
            field=models.IntegerField(default=0),
        ),
    ]
