# Generated by Django 4.2.16 on 2025-05-31 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0007_valve_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='valve',
            name='status',
        ),
    ]
