# Generated by Django 4.2.16 on 2025-06-02 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0008_remove_valve_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='valve',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
